# Generated by Django 5.2.17 on 2026-09-28 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavetype",
            name="requires_document",
        ),
    ]
