# Generated by Django 5.2.17 on 2026-09-29 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_remove_leavetype_requires_document"),
        ("projects", "0002_timeentry_hourly_cost_snapshot_timeentry_is_billable_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="employeehourlycost",
            name="unique_hourly_cost_effective_date",
        ),
        migrations.AddField(
            model_name="project",
            name="budget_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="hourly_cost_currency_snapshot",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddConstraint(
            model_name="employeehourlycost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("employee", "currency", "effective_from"),
                name="unique_hourly_cost_currency_effective_date",
            ),
        ),
    ]
